# Generated by Django 5.1.6 on 2025-02-25 15:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
